name = input("who are u?")
city = input("where do you live")
age = input('how old are you?')
hobby = input('what is your hobby')
movie = input('what is your favorit movie?')
food = input('what is your favorit food?')

print("------YOUR DETAILS FIELD BY YOU-----")
print("NAME:",name)
print("city", city)
print("age:", age)
print("hobby:", hobby)
print("movie:", movie)
print("food:",food)
print("----THE END----")